### ISSUE TITLE
FR: Add timer

### ISSUE THREAD

**Issue by jurialmunkey** [eonpatapon/gnome-shell-extension-caffeine#105]
Not so much an issue as a feature request, but I would love to see this extension incorporate a timer so you could, for instance, set it to keep awake for 30mins. I'll often be watching something in bed before I go to sleep and if I fall asleep whilst watching then my laptop battery will be dead when I wake up. Having an auto-disable timer would still allow my laptop to suspend after a set period. Thanks :)

**Comment by strugee** [comment]
I used to use Caffeine for macOS and it worked similarly to this. You could right-click and it would give you options for 5 minutes, 10 minutes, etc. all the way up to 5 hours and indefinitely. It's nice.

**Comment by pakaoraki** [comment]
I add a timer, similar to what Caffeine in LineageOS does.
![screenshot-timer-on](https://user-images.githubusercontent.com/83842133/200126915-8d607fcc-427f-4449-962d-a3307c47170e.png)

Source: [https://github.com/pakaoraki/gnome-shell-extension-caffeine](https://github.com/pakaoraki/gnome-shell-extension-caffeine)

Let us know if it's still something wanted in this gnome extension, maybe the creator would like to add this.

**Comment by stuarthayhurst** [comment]
With #216 merged, can this be closed?
