### ISSUE TITLE
suspend notification center

### ISSUE THREAD

**Issue by guilhem** [eonpatapon/gnome-shell-extension-caffeine#110]
When using caffeine during a presentation, it would be awesome to be able to block notification system.

No more private lovely message during a talk :p

**Comment by supervacuo** [comment]
in the mean-time, you could use the "[Do Not Disturb Button](https://extensions.gnome.org/extension/964/do-not-disturb-button/)"

**Comment by stuarthayhurst** [comment]
> in the mean-time, you could use the "[Do Not Disturb Button](https://extensions.gnome.org/extension/964/do-not-disturb-button/)" extension

This seems like the cleaner solution, can this be closed?

**Comment by eonpatapon** [comment]
This extension seems abandoned

I think this kind of feature is orthogonal to caffeine.

**Comment by stuarthayhurst** [comment]
> This extension seems abandoned

Oops, misread their comment. I thought they meant the "Do not disturb" switch in GNOME in the notification draw, which also works as a solution.

**Comment by stuarthayhurst** [comment]
Closing, as it's out of scope and there are alternatives purpose built for this, and also in GNOME already (Do not disturb switch in notification tray)
