### ISSUE TITLE
Xscreensaver Support

### ISSUE THREAD

**Issue by carlinux** [eonpatapon/gnome-shell-extension-caffeine#119]
Since i'm using xscreensaver to avoid the own unbearable screensaver of an OLED tv, i wonder if would be possible to give support to the xscreensaver daemon.
There's[ work done ](https://extensions.gnome.org/extension/749/caffeine-for-xscreensaver/)but outdated and it doesn't activate cause that.

**Comment by zachd** [comment]
Hi, you might be interested in [faux-gnome-screensaver](https://github.com/jefferyto/faux-gnome-screensaver), as it adds caffeine compatibility to xscreensaver.

**Comment by greatquux** [comment]
I forked and created a version with very simple support for XScreenSaver here https://github.com/greatquux/gnome-shell-extension-caffeine

**Comment by altsalt** [comment]
This seems related to issue #4 and #47. It also seems that @greatquux submitted PR #176 (which I will be trying out shortly). Issue #80 may also be related, but that functionality may be out of scope for this project.

Caffeine has been a great extension, and I've just ignored the lack of screensaver suspension for however long. That said, it sure would be nice.

I see the maintainer request and hope that someone comes along with the bandwidth to step up. Thanks for all of your efforts @eonpatapon !

**Comment by greatquux** [comment]
@altsalt just a quick note, this really is very quick-and-dirty ;) all it does is tell xscreensaver to stop when you turn caffeine on, and start it up again when you click it off.  if anything in the background starts up xscreensaver then the icon will be out of sync.

**Comment by eonpatapon** [comment]
As mentionned in the PR, it would be best to use https://man.archlinux.org/man/xscreensaver-systemd.6.en

**Comment by stuarthayhurst** [comment]
Closing with #260
