### ISSUE TITLE
Incompatible with gnome-shell 3.29 (libmutter-3)

### ISSUE THREAD

**Issue by smcv** [eonpatapon/gnome-shell-extension-caffeine#123]
libmutter 3.29 removes the `MetaScreen`, which is GNOME Shell's `global.screen`: https://bugzilla.gnome.org/show_bug.cgi?id=759538

It looks as though caffeine uses `global.screen` and so will need changes for 3.29.

**Comment by bulletmark** [comment]
Stock Arch Linux updated to GNOME 3.30 today and so Caffeine dies with this error.

All Arch derivatives will update soon as well so plenty of people will be coming here ...

**Comment by smcv** [comment]
Fixed by #126
