### ISSUE TITLE
Online Accounts status wrong after locking the screen with extension enabled

### ISSUE THREAD

**Issue by SietsevanderMolen** [eonpatapon/gnome-shell-extension-caffeine#13]
Using this extension on Gnome 3.8.1 triggers this bug:

https://bugzilla.gnome.org/show_bug.cgi?id=700168

You might have to try to lock/unlock two or three times in case it doesn't show up at first

**Comment by stuarthayhurst** [comment]
Reading the linked thread, the area of the shell that has the issue has been redesigned, and the issue went away. Also, it seems the issue was in GNOME Shell, and not extension-side anyway.
