### ISSUE TITLE
no icon with 3.31.90

### ISSUE THREAD

**Issue by jbicha** [eonpatapon/gnome-shell-extension-caffeine#134]
- Ubuntu 19.04 and Debian Unstable
- Ubuntu and default GNOME sessions
- gnome-shell 3.31.90
- gnome-shell-extension-caffeine 0~git20181105-1 (Debian package)

After upgrading to gnome-shell 3.31.90, the top bar icon for the Caffeine extension no longer shows up. I can click the space where the icon should be and I get the notifications that "auto suspend and screensaver" are enabled or disabled.

**Comment by adovbos** [comment]
same with Fedora 30 gnome 3.32

**Comment by lfelipe1501** [comment]
yes in the new Gnome 3.32 is the same Bug :face_with_head_bandage:

**Comment by corebots** [comment]
thanks in advance for updating to support 3.32, looking forward to it.

**Comment by coxackie** [comment]
Can confirm the loss of icon as well. Seems like a lot of the extensions were affected this way with Gnome 3.32.

**Comment by corebots** [comment]
anyone knows what's this or why it's been under review for like a year already? https://extensions.gnome.org/review/7842 thanks

**Comment by demolanguage** [comment]
The icon does not display only with the adwaita icon theme.

**Comment by mirko-laruina** [comment]
Just made a PR using the solution referenced by @demolanguage, let me know if it works correctly.

**Comment by ogarcia** [comment]
@mirko-laruina it works perfect for me :-)

**Comment by coxackie** [comment]
confirming that it works - many thanks @mirko-laruina!

**Comment by mirko-laruina** [comment]
Nice, now waiting for it to be merged!

**Comment by jonafato** [comment]
It looks like this issue was fixed by #137 and should be closed.
