### ISSUE TITLE
Get error on ubuntu 18.04 after last update

### ISSUE THREAD

**Issue by caseca** [eonpatapon/gnome-shell-extension-caffeine#143]
Extension "caffeine@patapon.info" had error: Error: No signal 'in-fullscreen-changed' on object 'MetaDisplay'

**Comment by prascher** [comment]
I tried to install it from the gnome extensions site and it just throws errors

**Comment by mbradford-verys** [comment]
Same issue here

**Comment by prascher** [comment]
It appears to be working from extensions.gnome.org now.

**Comment by SuperboGiuseppe** [comment]
Undefined error also for me. (Ubuntu 18.04.2, GNOME 3.28.3)

**Comment by eonpatapon** [comment]
Should be fixed with the latest version

**Comment by SuperboGiuseppe** [comment]
After cleaning the extension folder from the old version and installing the newest version, it works as before!

**Comment by darwin2k** [comment]
> After cleaning the extension folder from the old version and installing the newest version, it works as before!

Deleted the extension dir and reinstalled- but still error :(

**Comment by SuperboGiuseppe** [comment]
Restarting the PC helped me

**Comment by darwin2k** [comment]
> Restarting the PC helped me

Worked for me - thanks!

**Comment by jonafato** [comment]
Looks like this issue is fixed and should be closed.
