### ISSUE TITLE
Closing full screen application toggles caffeine off

### ISSUE THREAD

**Issue by QuestofIranon** [eonpatapon/gnome-shell-extension-caffeine#145]
Caffeine is toggled off whenever a full screen application is closed, even if it was toggled before opening the full screen application.

**Comment by eonpatapon** [comment]
You mean you toggled it manually then run a full screen application ?

**Comment by ckotte** [comment]
I cannot confirm this. Caffeine stays enabled if I switch to full screen, switch back to normal or switch to full screen and close the app with alt+f4.

**Comment by openjck** [comment]
I also cannot confirm this.

**Comment by QuestofIranon** [comment]
I can't try to reproduce this since I no longer have access to a Mac.

**Comment by QuestofIranon** [comment]
I can confirm that I haven't seen this problem in a few years.  (Sorry for my original comment, thought this was something else.)
