### ISSUE TITLE
Needs Update for GNOME 3.36

### ISSUE THREAD

**Issue by mon0theist** [eonpatapon/gnome-shell-extension-caffeine#154]
Keeps giving Error when viewing Installed Extensions on extensions.gnome.org

**Comment by LordSushiPhoenix** [comment]
The issue is only present on Wayland. My laptop uses Wayland and the extension is incompatible with 3.36, my desktop is on Xorg and it works fine.

**Comment by devillove084** [comment]
please update for wayland user.....

**Comment by Bruce-YC** [comment]
The fix is pretty easy... Just delete the line 313-314 in extension.js
`    let theme = imports.gi.Gtk.IconTheme.get_default();
    theme.append_search_path(extensionMeta.path + "/icons");`
and then install the extension normally.

**Comment by bulletmark** [comment]
@Bruce-YC thanks, can confirm that fixes it for me also.

**Comment by sanjayankur31** [comment]
> The fix is pretty easy... Just delete the line 313-314 in extension.js
> ` let theme = imports.gi.Gtk.IconTheme.get_default();`
> ` theme.append_search_path(extensionMeta.path + "/icons");`
> and then install the extension normally.

Could you open a PR with the fix please @Bruce-YC : that'll make it easier for the maintainer to push the update.

**Comment by sanjayankur31** [comment]
(I had a few minutes on my hands, so I opened the PR)
