### ISSUE TITLE
Toggling Caffeine using touch screen not working

### ISSUE THREAD

**Issue by MrSSvard** [eonpatapon/gnome-shell-extension-caffeine#156]
Not sure if this is a feature request or a bug report but anyways. Pressing the coffee cup app indicator using touch screen does nothing. The expected behavior would be toggling caffeine like when you press it since that's what happens when you click it with a mouse.

My system:
Surface GO
Fedora silverblue 31 / Fedora Silverblue 32
Gnome Shell 3.34 on Wayland / Gnome Shell 3.36 on Wayland

**Comment by jlempen** [comment]
Hey MrSSvard,
That's an easy fix. In `extension.js`, locate the line
`        this.actor.connect('button-press-event', this.toggleState.bind(this));
and add the following line directly underneath:
`        this.actor.connect('touch-event', this.toggleState.bind(this));

Save the file and reboot.
