### ISSUE TITLE
Wayland: specified applications don't enable Caffeine automatically

### ISSUE THREAD

**Issue by ignapk** [eonpatapon/gnome-shell-extension-caffeine#163]
On Wayland after adding application in Caffeine settings, it doesn't enable Caffeine automatically when launched. The only way to enable Caffeine with specified application is to re-enable the extension while said application is already launched, then it correctly enables Caffeine, and correctly disables Caffeine after closing the application.

This issue doesn't occur on Xorg

Tested and confirmed on 3.36 and 3.37.90 (3.38)

**Comment by eonpatapon** [comment]
@ignapk could you test the #166 PR to validate it fixes your problems ?
