### ISSUE TITLE
not working for gnome 3.36.5

### ISSUE THREAD

**Issue by XueqiangDong** [eonpatapon/gnome-shell-extension-caffeine#164]
OS: Archlinux-lts
Gnome desktop version: 3.36.5-1

It's not working, there is no effect enable/disable caffeine

**Comment by bulletmark** [comment]
I'm on fully up to date Arch Linux and it works fine for me. Ensure the problem is not due to the presence of another extension.

**Comment by ckotte** [comment]
It was working for me on 3.36 as well. It also works on 3.38...

**Comment by stuarthayhurst** [comment]
With no log and an unsupported version of GNOME not much can be done here, please open a new issue with a log attached if you can reproduce this on GNOME 43 or GNOME 44, thanks
