### ISSUE TITLE
Error at upgrade? Relogin needed!

### ISSUE THREAD

**Issue by cjauvin** [eonpatapon/gnome-shell-extension-caffeine#170]
Thanks for the extension, even though it's a simple functionality, I cannot live without it! Three things I want to mention:

1. For a long while I've been using this on Ubuntu 20.04: https://launchpad.net/caffeine, without realizing that there was a more modern version.. so perhaps make it a bit more clear on the extension page somehow?

2. Today it was the first time I had to upgrade this Caffeine and when I did it through Firefox the result was just a red ERROR button without any error message (or so that I could find); I had to use Looking Glass to inspect the error and see that it needs relogin.. would there be a way to make this more clear maybe?

3. Not sure if it's easy or desirable but the only thing missing for me is a way to activate it using a keyboard shortcut.. I considered learning about Gnome Extension coding just to submit a PR, but I'm not ready to do it yet, so just mentioning it here.

**Comment by eonpatapon** [comment]
Sorry, It was just a bad timing for you to update at this time as I've uploaded a buggy version this morning (v36)

Should be working fine with the latest one (v37)

**Comment by eonpatapon** [comment]
https://launchpad.net/caffeine is completely different project I belevie. It's not a gnome shell extension

**Comment by cjauvin** [comment]
> https://launchpad.net/caffeine is completely different project I belevie. It's not a gnome shell extension

I now understand that but I'm just saying that for a new Ubuntu user searching for "Caffeine", it might be a bit confusing (I know it was for me, until yesterday).

**Comment by ckotte** [comment]
Regarding point number 3. Looks like it's not possible to activate it through keyboard. I tried to implement it, but GNOME shell doesn't properly handle key presses.

**Comment by stuarthayhurst** [comment]
As far as I know, point 2 is fairly standard for GNOME extensions, and a reboot / relogin will normally fix it.
As for point 3, this seems to be working in `master`, unless I've misunderstood, can this be closed?

**Comment by stuarthayhurst** [comment]
Closing as all points have been addressed
