### ISSUE TITLE
3.37 is not working.  You need to go back one version and test for 3.38, not 3.37.

### ISSUE THREAD

**Issue by lsatenstein** [eonpatapon/gnome-shell-extension-caffeine#171]

**Comment by ckotte** [comment]
can you please be more precise? test for 3.38 instead of 3.37?

**Comment by lsatenstein** [comment]
Ran the update, nothing happens. zero.  The on/off toggle from extensions / gnome-tweaktool immediately blocks with a [ERROR] I am using Fedora 33 on the desktop and also pop-os on the laptop. 

Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

 

    On Tuesday, November 24, 2020, 2:22:33 p.m. EST, Christian Kotte <notifications@github.com> wrote:  
 
 


can you please be more precise? test for 3.38 instead of 3.37?

**Comment by ckotte** [comment]
can you do alt+f2, type lg, click on extensions tab, click on show errors under caffeine and paste the error

**Comment by lsatenstein** [comment]
First feedback.  Works just fine with Fedora 33.

Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

 

    On Tuesday, November 24, 2020, 3:08:18 p.m. EST, Christian Kotte <notifications@github.com> wrote:  
 
 


can you do alt+f2, type lg, click on extensions tab, click on show errors under caffeine and paste the error

**Comment by lsatenstein** [comment]
ERROR MESSAGE      expected expression   got <  

Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

 

    On Tuesday, November 24, 2020, 3:08:18 p.m. EST, Christian Kotte <notifications@github.com> wrote:  
 
 


can you do alt+f2, type lg, click on extensions tab, click on show errors under caffeine and paste the error

**Comment by lsatenstein** [comment]
I went to the directory. There was a caffeine extension (not yours) name xcaffeine@asegner.gmail.com    rm -rf this directory and resinstalled 
caffeine, and all is OK
Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

 

    On Tuesday, November 24, 2020, 3:08:18 p.m. EST, Christian Kotte <notifications@github.com> wrote:  
 
 


can you do alt+f2, type lg, click on extensions tab, click on show errors under caffeine and paste the error

**Comment by lsatenstein** [comment]
README in the rm'd extension
branched from https://extensions.gnome.org/extension/517/caffeine/ to work with Xscreensaver   

Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

 

    On Tuesday, November 24, 2020, 2:22:33 p.m. EST, Christian Kotte <notifications@github.com> wrote:  
 
 


can you please be more precise? test for 3.38 instead of 3.37?

**Comment by ckotte** [comment]
Can you close this ticket then?

**Comment by nicekiwi** [comment]
@ckotte this extension as v38 is broken in Gnome 3.88 on Ubuntu 20.10. v37 worked, but v38 breaks.
