### ISSUE TITLE
polish l10n

### ISSUE THREAD

**Issue by anmar16** [eonpatapon/gnome-shell-extension-caffeine#172]
I'd like to ask if you could correct polish locale files. In these file "automatycze" string should be changed to "automatyczne". I tried to do it in local files but I suppose there is string length problem. Thanks in advance.

**Comment by stuarthayhurst** [comment]
https://github.com/eonpatapon/gnome-shell-extension-caffeine/blob/5ccb88d1ef0e1e1149fa1f346adf84bec036ec2b/caffeine%40patapon.info/locale/pl/LC_MESSAGES/gnome-shell-extension-caffeine.po#L307

The impacted translation strings are currently marked as fuzzy, so they're not used in production as they're probably not quite right. If you want to update the Polish translation files, they're found [here](https://github.com/eonpatapon/gnome-shell-extension-caffeine/blob/master/caffeine%40patapon.info/locale/pl/LC_MESSAGES/gnome-shell-extension-caffeine.po)

**Comment by stuarthayhurst** [comment]
Closing, as the impacted translation string isn't used anymore
