### ISSUE TITLE
Add support for GNOME 40

### ISSUE THREAD

**Issue by frandieguez** [eonpatapon/gnome-shell-extension-caffeine#175]
**Extension Information**

* Shell Version: GNOME 40
* Extension Version: 34
* Install method: extension.gnome.org
* OS: Fedora 33 with GNOME 40 alfa installed via `sudo dnf copr enable haeckerfelix/gnome-shell-40 &&  sudo dnf update`

**Describe the bug**
GNOME 40 is already in alfa and it forces the usage of GTK4 for extensions dialogs.

This extensions works pretty well until you open the preferences panel with the next output:

```
Error: No property margin on GtkBox

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:63:40
  CaffeineWidget@/home/fran/.local/share/gnome-shell/extensions/caffeine@patapon.info/prefs.js:42:31
  buildPrefsWidget@/home/fran/.local/share/gnome-shell/extensions/caffeine@patapon.info/prefs.js:296:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Please consider update to GTK4, to keep this awesome extension usable

**Comment by corebots** [comment]
I second this request; GNOME 40 is on beta now, would love to see this excellent extension working there!

**Comment by Luctins** [comment]
I've tested this on a GnomeOS VM, seems that most of the porting is related to the pref's window.
As I use this ext a lot to, I'll try to eventually make a PR porting this to Gnome40.

**Comment by 5n00p4eg** [comment]
Just upgraded to Fedora 34 Beta with Gnome 40, waiting for a new version as well!! Thanks, guys for contributing, it is a very useful plugin!

**Comment by kaechele** [comment]
The extension itself works, as long as you don't need to touch the prefs panel.

I've rewritten the prefs dialog for GNOME 40 and Gtk4.
If anyone would like to test: https://github.com/kaechele/gnome-shell-extension-caffeine
I've only tested that all basic functionality is still working. I have not tested this version on anything older than GNOME 40 and assume it won't work there.

**Comment by LyesSaadi** [comment]
@kaechele's rewrite works for me! Tested quickly every feature. Everything seems to work (even the app list) except "Remember state" and "Night Light", but I'm not sure if that's either an extension bug or an issue on my end since it does toggle successfully the parameter in dconf.

Anyway, a great work overall!

**Comment by eonpatapon** [comment]
@kaechele nice!

**Comment by HougeLangley** [comment]
![image](https://user-images.githubusercontent.com/1161594/113158530-744a0d00-926e-11eb-822a-35e49c16e9b1.png)

Gnome 40 offical released.

**Comment by kaechele** [comment]
A rework of my initial port is now a pull request #179

**Comment by toMeloos** [comment]
Since that PR is merged, this issue can be closed?

**Comment by eonpatapon** [comment]
Yes, thanks to @kaechele 

I've uploaded it to e.g.o
