### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by SDakaXvost** [eonpatapon/gnome-shell-extension-caffeine#178]
Good health! I did the translation into Ukrainian. It would be great if this translation was included in the extension.
[uk.zip](https://github.com/eonpatapon/gnome-shell-extension-caffeine/files/6259382/uk.zip)

**Comment by stuarthayhurst** [comment]
If you can update this for the current contents of `master`, I'll bundle this into a pull request for you :)

**Comment by stuarthayhurst** [comment]
Closing, since the translation is outdated and this issue is 3 years old. Updated translations are still welcome of course (especially as a pull request, but issues work if you're not sure how)
