### ISSUE TITLE
GNOME 41 compatibility

### ISSUE THREAD

**Issue by frandieguez** [eonpatapon/gnome-shell-extension-caffeine#186]
In some days GNOME 41 will be released and I have tested your extension by simply adding the new version to the `caffeine@patapon.info/metadata.json` file.

```
    "shell-version": [
        "40.1",
        "40.1",
        "41"
    ],
```

It will be awesome to have your extension compatible on day-one.

**Comment by ReillyBrogan** [comment]
I believe it's fine to have the shell version without the point release.

```
    "shell-version": [
        "40",
        "41"
    ],
```
