### ISSUE TITLE
Not a bug but a request - Allow black screen but not suspend

### ISSUE THREAD

**Issue by ghost** [eonpatapon/gnome-shell-extension-caffeine#188]
Hi,

thanks for this extensions.

Would it be possible to add an option to authorize the screen to be switch off but not allow the suspend ?

It could be : 
-1st clic=allow black screen / disable suspend
- 2nd clic=disable blackscreen / disable suspend
-  3rd clic=allow black screen / allow suspend (=return to normal use)

With a "progressive" smoke icon above the cup or a saucer under :)

Regards,

**Comment by biji** [comment]
Would be great if caffeine supports this. My use case is when downloading games from steam, prevent suspend but let screen off

probably similiar to: https://github.com/eonpatapon/gnome-shell-extension-caffeine/issues/80 https://github.com/eonpatapon/gnome-shell-extension-caffeine/issues/121

Thanks

**Comment by biji** [comment]
When `this option` is enabled, inhibit flags should be `8` instead of `12`:

          <doc:para>
            The flags parameter must include at least one of the following:
            <doc:list>
              <doc:item>
                <doc:term>1</doc:term>
                <doc:definition>Inhibit logging out</doc:definition>
              </doc:item>
              <doc:item>
                <doc:term>2</doc:term>
                <doc:definition>Inhibit user switching</doc:definition>
              </doc:item>
              <doc:item>
                <doc:term>4</doc:term>
                <doc:definition>Inhibit suspending the session or computer</doc:definition>
              </doc:item>
              <doc:item>
                <doc:term>8</doc:term>
                <doc:definition>Inhibit the session being marked as idle</doc:definition>
              </doc:item>
              <doc:item>
                <doc:term>16</doc:term>
                <doc:definition>Inhibit auto-mounting removable media for the session</doc:definition>
              </doc:item>
            </doc:list>
            Values for flags may be bitwise or'ed together.
          </doc:para>

**Comment by eonpatapon** [comment]
Implemented in https://github.com/eonpatapon/gnome-shell-extension-caffeine/pull/216

**Comment by eonpatapon** [comment]
However it's not exactly like proposed. It's only a setting in the preferences

Feel free to open a new issue if you'd like something else
