### ISSUE TITLE
Let user define a shortkey which trigger Caffine. Save a LOT of time.

### ISSUE THREAD

**Issue by PranavBhattarai** [eonpatapon/gnome-shell-extension-caffeine#189]
I love this extension so far. It's simple and perfect. 
But there is something annoying when u have to click Caffeine at least 20 times a day.
20 x 4 sec = 80 sec = 1min + 20sec. For vim users, this is a lot. Anyone who is more keyboard-driven, this can be unacceptable. 
I think it would be really cool if there is some sort of command to activate Caffeine mode.
So I can use this "command" in `GNOME settings > Keyboard > View and Customize Shortcuts > Customize Shortcuts > +` to add our Caffeine command to activate and deactivate extension. Sort of like:
```
gnome-extensions activate caffeine@patapon.info
gnome-extensions deactivate caffeine@patapon.info
```

Another way to roll this feature is, to add another option here in this section:
![image](https://user-images.githubusercontent.com/32763112/150135877-fad511f9-64c6-4210-9282-1888930170a5.png)
I have seen other gnome extensions successfully rolling their own shortkey (like [Dash-To-Panel](https://github.com/home-sweet-gnome/dash-to-panel): User can hide/unhide panel using their own shortkey).

Something like:
Super + C = Activate Caffine
Super + C = Deactive Caffine         -----------  _(if caffine is already activate)_

**Comment by eonpatapon** [comment]
I agree it would be a nice addition if it's possible to define shortcuts in an extension

Revelant function to do this seems to be Main.wm.addKeybinding
https://github.com/home-sweet-gnome/dash-to-panel/blob/81af73b23911cbbdce807566ed6ef2a864417d6c/utils.js#L404

Also maybe interesting to look at: https://mail.gnome.org/archives/gnome-shell-list/2014-September/msg00017.html

PR welcome!

**Comment by PranavBhattarai** [comment]
> PR welcome!

😢😢😢

**Comment by nnleaf** [comment]
Would love this feature, especially so I can write my own scripts to de/activate when plugging into power.

**Comment by vijay-prema** [comment]
think if someone figures out how to change caffiene from terminal it can be done easily https://github.com/eonpatapon/gnome-shell-extension-caffeine/issues/148

**Comment by eonpatapon** [comment]
Can someone try https://github.com/eonpatapon/gnome-shell-extension-caffeine/pull/205 for the shortcut part ?

**Comment by PranavBhattarai** [comment]
@eonpatapon After uninstalling the Caffeine extension which I downloaded from the gnome-extension website, I downloaded the master's zip and extracted it and run `make build` as you can see:
  ```
  ⟹  make build
./update-locale.sh
xgettext: warning: a fallback ITS rule file '/usr/share/gettext-0.21/its/gsettings.its' is used; it may not be in sync with the upstream
locale/cs/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/de/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/es/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/fr/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/hu/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/it_IT/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/ja/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/nl/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/pl/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/pt_BR/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/pt_PT/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/ru/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/sk/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/sv/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/tr/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
locale/zh_CN/LC_MESSAGES/gnome-shell-extension-caffeine.po
....... done.
glib-compile-schemas --strict --targetdir=caffeine@patapon.info/schemas/ caffeine@patapon.info/schemas
~/Downloads/gnome-shell-extension-caffeine-master
  ⟹
  ```
  And run `make install`:
  ```
    ⟹  make install
install -d ~/.local/share/gnome-shell/extensions
cp -a caffeine@patapon.info/ ~/.local/share/gnome-shell/extensions/
```
And I copied as mentioned in above command's output.
And I had to restart the PC in order to see Caffeine in the Extension app because login-and-logout didn't work.

But I didn't see the option like **Toogle Shortcut** when I opened my Caffeine setting:
![image](https://user-images.githubusercontent.com/32763112/176142257-631e4896-1c68-4139-b6c7-a4a7686d8831.png)

Mine has still the old layout. Does this mean my version of the extension is still old? The merge is made of master repo, right?  Did I do something wrong while installing? Let me know.

**Comment by eonpatapon** [comment]
@PranavBhattarai it's not merged yet, you have to checkout the branch of the PR to test it

**Comment by PranavBhattarai** [comment]
@eonpatapon It seems to be working fine. I set `Super + Y`for a shortkey

But I have one question though, when I run `journalctl /usr/bin/gnome-shell -f` command on both new patche or previous releases, I saw this error/warning/line:
 
 `Jun 28 15:18:05 x gnome-shell[2189]: g_settings_get_enum() called on key 'control-nightlight' which is not associated with an enumerated type`
 
 The 'message' doesn't change when I enable/disable Caffeine either through the GUI icon or the CLI icon. But it will give more messages the more I enable/disable the extension. Do you know why? 
 
 Other things was:
 - the installation process was weird. Not straightforward. -------->> Is this normal?
 - xgettext: warning: a fallback ITS rule file '/usr/share/gettext-0.21/its/gsettings.its' is used; it may not be in sync with the upstream
locale/cs/LC_MESSAGES/gnome-shell-extension-caffeine.po

**Comment by eonpatapon** [comment]
Thanks for the feedback

> But I have one question though, when I run `journalctl /usr/bin/gnome-shell -f` command on both new patch or previous releases, I saw this error/warning/line:
> 
> `Jun 28 15:18:05 x gnome-shell[2189]: g_settings_get_enum() called on key 'control-nightlight' which is not associated with an enumerated type`
> 
> The 'message' doesn't change when I enable/disable Caffeine either through the GUI icon or the CLI icon. But it will give more messages the more I enable/disable the extension. Do you know why?

Not sure this is related to caffeine because we use `_settings.get_value('control-nightlight');` and not `get_num`. Do you get this message only with caffeine ?

> Other _minor_ things were:
> 
>     * the installation process was weird. Not straightforward. -------->> Is this normal?

It is what it is :-) Most users will get the extension from extensions.gnome.org or their package manager anyway.

> ### Edit:
> 
>     * The Toggle Shortcut, the way it works is a bit weird.  It doesn't look smooth when the user tries to assign a new shortkey. But it **does** work and that matters.

What do you mean by it isn't smooth ? Sorry I don't have gnome-shell right now to test this.

**Comment by notabugwontfix** [comment]
> What do you mean by it isn't smooth ? Sorry I don't have gnome-shell right now to test this.

I think he means the shitty control I used for shortcut setting element :)
Anyway after #207 we can set bindings through GNOME Settings, so #205 is more friendly way to do it, but not necessary anymore.

**Comment by notabugwontfix** [comment]
Now I've made it look better.

[Kooha-06-29-2022-00-54-29.webm](https://user-images.githubusercontent.com/107809638/176308533-9dce8897-25ab-44e0-9282-62b57ef9a389.webm)
