### ISSUE TITLE
Touchscreen: double clicks & accidental toggles occur. Consider standard topbar menu instead

### ISSUE THREAD

**Issue by seltzered** [eonpatapon/gnome-shell-extension-caffeine#192]
Caffeine currently works as a single click button in the topbar, which works fine for indirect manipulation (i.e. mouse, trackpad) usecases but introduces the following problems when in direct manipulation (i.e. touchscreen) environments:

- Touching the caffeine icon ends up acting as two clicks - it seems near-impossible to toggle on a touchscreen.

- When doing a three-finger touchscreen gesture to get into the activities overview, depending on origin caffeine can accidentally get triggered.

With this in mind, I'd recommend considering a standard topbar modal to perform enable/disable. While it's two clicks instead of one, it may prevent the above two issues.

**Comment by PranavBhattarai** [comment]
This is a bad idea for those users who don't have a touchscreen display. Currently, we have a very straightforward mechanism to enable/disable Caffine. It doesn't look ugly giant which covers/bloats the taskbar.

I think 80% of Caffeine users have non-touch displays. So I don't think it is a good idea to provide a full-fledged menu to all those users who have been using Caffeine all these years.

I know there is a problem with enabling/disabling Caffeine with a human finger touch. I myself have a touchscreen laptop but I'm fine touching Caffeine with a touchpad.

So maybe we can introduce a "menu" option inside the Caffeine extension setting for touchscreen users to enable. Like:

i. Traditional Caffeine option ----------------> which I prefer regardless of touchscreen issue
ii. Modern Caffeine option ------------------> which you prefer. "Standard topbar modal" that give a sub-menu to enable/disable

How that sound?

**Comment by seltzered** [comment]
@PranavBhattarai Yeah, that could work. I'd suggest perhaps the 'standard topbar modal' be the default setting, the Gnome Human Interface Guidelines on first glance doesn't seem to have specific guidelines around the top bar, but does have some principles around pointer & touch in https://developer.gnome.org/hig/guidelines/pointer-touch.html : 

- _"Click targets should be large enough to be comfortably used with different pointing devices and physical abilities."_

- _"Buttons and controls which are only available on some pointing devices should not be exclusively relied upon for particular actions."_

**Comment by stuarthayhurst** [comment]
This shouldn't be an issue in GNOME 43 now #216 is merged, as it uses the standard Quick Settings menu.

Can this be closed?
