### ISSUE TITLE
Extension disabled in GNOME 43

### ISSUE THREAD

**Issue by lazytownfan** [eonpatapon/gnome-shell-extension-caffeine#212]
Debian Sid/Unstable recently received GNOME 43, so this extension is disabled by default.

The last version of GNOME this extension's metadata hard codes is currently GNOME 42.

However, manually changing the metadata will fix the issue to include GNOME 43, as done in PR #211.

(The PR's comments also indicated that this fix is needed in Fedora 37.)

**Comment by stuarthayhurst** [comment]
@eonpatapon Can this be closed?

**Comment by lazytownfan** [comment]
Closing, as PR #211 was accepted on Oct 10, 2022
