### ISSUE TITLE
Localization not working (it_IT)

### ISSUE THREAD

**Issue by amivaleo** [eonpatapon/gnome-shell-extension-caffeine#225]
Hi!

This extension doesn't load the right localization in my system (it_IT).
I found the right locale folder in the extension directory, but nothing is translated.

Cheers!

**Comment by stuarthayhurst** [comment]
#221 Should cover most of this, I think it just needs updating since the last changes?

**Comment by amivaleo** [comment]
Yes, I can help, I'd be glad to help.
So, do I start from scratches or from the file that @stuarthayhurst linked?

**Comment by stuarthayhurst** [comment]
You could ask @albanobattistella what their plans are on that pull request, as that translation should be mostly complete.

**Comment by stuarthayhurst** [comment]
#221 seems to have stalled, feel free to submit another PR, I'll close the other in favour of the new one when it's ready to merge
