### ISSUE TITLE
Some applications not recognized as running

### ISSUE THREAD

**Issue by bhartshorn** [eonpatapon/gnome-shell-extension-caffeine#233]
Hi all,

I'm trying to use the caffeine Apps recognition feature with a couple games and it simply doesn't recognize that they're running. I suspect it's applications running in xwayland which are not recognized, though I haven't dug in to it. The two applications I've confirmed so far are "Minetest" and "Cemu". Caffeine *does* successfully recognize "gnome-terminal", even on the "Focus" setting.

I'm running Caffeine version 44 on Gnome 43.3, fully updated Archlinux system.

**Comment by hehellooedas** [comment]
caffeine can't be used on GNOME44

**Comment by bhartshorn** [comment]
Thanks but this was on Gnome 43 and Caffeine works well otherwise.

**Comment by stuarthayhurst** [comment]
Are you able to test on pure X11? If XWayland is the culprit, that would help narrow it down.

**Comment by bhartshorn** [comment]
I should be able to test on X11, I'll give it a shot when I can.

**Comment by bhartshorn** [comment]
Just checking back in on this - the two applications I mentioned are now recognized, I'm not sure if they are running as wayland-native apps now or if y'all fixed a bug on your end, but this seems to be solved. Thanks for your efforts!
