### ISSUE TITLE
Add support for GNOME 44

### ISSUE THREAD

**Issue by Scotty-Trees** [eonpatapon/gnome-shell-extension-caffeine#235]
Greetings,

I know it's still a little bit early, but Gnome 44 alpha/beta are out now for testing purposes and I was wondering if/when the extension will be updated? Some extensions are already being updated to support the latest which is very nice to see. The final release for Gnome 44 should be on March 22nd, 2023 btw. Thank you for your time and thank you for making an amazing extension I couldn't live without! Cheers

**Comment by Scotty-Trees** [comment]
Ah awesome to hear, sorry I must have missed that, feel free to close this issue and I'll follow the progress over there, thank you.

**Comment by stuarthayhurst** [comment]
Initial support done (#231).
I've opened #236 to discuss the new subtitles, if we end up using them
