### ISSUE TITLE
v45 - GLib.FileError: Failed to open file <home>/.local/share/gnome-shell/extensions/caffeine@patapon.info/schemas/gschemas.compiled: open() failed: No such file or directory

### ISSUE THREAD

**Issue by zeten30** [eonpatapon/gnome-shell-extension-caffeine#244]
GLib.FileError: Failed to open file <home>/.local/share/gnome-shell/extensions/caffeine@patapon.info/schemas/gschemas.compiled: open() failed: No such file or directory

Extension doesn't work due to missing gschemas.compiled.

This a fresh install on gnome 44 testing box. Update from previous is fine - file is already present.

**Comment by eonpatapon** [comment]
How did you install the extension ?

**Comment by zeten30** [comment]
From extensions.gnome.org Firefox.

**Comment by eonpatapon** [comment]
That's strange because the zip from e.g.o has the gschemas.compiled file

https://extensions.gnome.org/review/download/39168.shell-extension.zip

**Comment by stuarthayhurst** [comment]
Might be related to GNOME 44 preferring the schemas source file, the compiling it locally. Extensions targeting GNOME 44 only have to ship the source and not the compiled file, extensions targeting GNOME 43 and earlier too can include both.

**Comment by stuarthayhurst** [comment]
The extensions site has a strange way of loading extensions, there's a chance it's removing the compiled schema, can't compile the one it now wants because the source is missing, and then the file is missing when the extension attempts to load.

**Comment by eonpatapon** [comment]
Do you know if I only ship the schema definition, will it work in 43 also ?

**Comment by stuarthayhurst** [comment]
AFAIK, it won't work without the compiled schemas for earlier versions. I ship both for my extensions, with no issues so far.

Related merge request to GNOME Shell: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2638

**Comment by zeten30** [comment]
Something changed in the install process, yes.

```
~/Downloads 
> gnome-extensions install caffeinepatapon.info.v45.shell-extension.zip
No schema files found: removed existing output file.
```

Looks like that XML source schema should be in the package.

**Comment by zeten30** [comment]
I've tested other extension with schema included and installation went just fine.

pull/245 should fix it:)

Thank you

**Comment by eonpatapon** [comment]
Uploaded a new version on e.g.o
