### ISSUE TITLE
no cup icon showing

### ISSUE THREAD

**Issue by xevilstar** [eonpatapon/gnome-shell-extension-caffeine#247]
no cup icon showing on gnome 44.rc

**Comment by stuarthayhurst** [comment]
Can you attach a log? You can find this using `journalctl -xb`, then looking for anything related to the extension.

Can you also make sure that the value of "Show status indicator in top panel" isn't set to never? It might also be then it's set to "Only when active", when you wanted "Always"

**Comment by xevilstar** [comment]
it was the show status indicator in top panel.
I feel so stupid... sorry... but in the past the value must have been always by default can it be like it was ?

Thanks for your time and sorry for my dumbness

**Comment by stuarthayhurst** [comment]
No worries, glad there's no issue to fix :)

As Caffeine adds itself to the Quick Settings menu, to stay consistent with the rest of GNOME, it should only really show itself when it's active. This makes sense as the default, but users that want it to always be visible are given the option in the extension's settings.
