### ISSUE TITLE
Caffeine displayed under Background Apps (GNOME 44)

### ISSUE THREAD

**Issue by flipflop97** [eonpatapon/gnome-shell-extension-caffeine#249]
The Caffeine toggle is displayed under Background Apps on GNOME 44, it would be more logical if it was with the other toggles.

![image](https://user-images.githubusercontent.com/13943260/226114825-c65d966d-9dac-4079-abc9-826577b5a6b4.png)

**Comment by stuarthayhurst** [comment]
Can you name any apps that run in the background? I'll set up a test environment and try fix this.

**Comment by flipflop97** [comment]
> Can you name any apps that run in the background? I'll set up a test environment and try fix this.

Thanks! Three apps that are pretty much always there for me are [Calendar](https://beta.flathub.org/apps/org.gnome.Calendar), [Damask](https://beta.flathub.org/apps/app.drey.Damask) and [Reminders](https://beta.flathub.org/apps/io.github.dgsasha.Remembrance).

**Comment by stuarthayhurst** [comment]
#250 should close this, feel free to test it :)

**Comment by flipflop97** [comment]
> #250 should close this, feel free to test it :)

It does, thanks!
