### ISSUE TITLE
Gnome shell 44 crashed while logging out.

### ISSUE THREAD

**Issue by plumlis** [eonpatapon/gnome-shell-extension-caffeine#254]
Fedora 38 64 bit
Gnome shell 44
gnome-shell-extension-caffeine v46

1,Enable caffeine extension ( No need to keep caffeine on. Just enable the extension)
2,Log out 
3,Gnome shell crashed.

Object .Gjs_caffeine_patapon_info_extension_CaffeineToggle (0x5634c102f5d0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfunc

**Comment by pakaoraki** [comment]
This should fix this error #252 ([commit](https://github.com/eonpatapon/gnome-shell-extension-caffeine/pull/252/commits/ac8c06be5cfdd49218babdd19845aaed553e3137))
