### ISSUE TITLE
Can not change any settings, using opensuse leap 15.4

### ISSUE THREAD

**Issue by joaoseixas88** [eonpatapon/gnome-shell-extension-caffeine#256]
The settings of extension caffeine@patapon.info had an error:
```
SyntaxError: expected property name, got '{'
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:216:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by stuarthayhurst** [comment]
Can you attach the output from `journalctl -xb` when the issue happens? That output gives the line number of the issue as well.

**Comment by joaoseixas88** [comment]
> Can you attach the output from `journalctl -xb` when the issue happens? That output gives the line number of the issue as well.
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009d3ff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000009d400-0x000000000009ffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000000100000-0x0000000009bfefff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000009bff000-0x0000000009ffffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a000000-0x000000000a1fffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a200000-0x000000000a20dfff] ACPI NVS
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a20e000-0x000000000affffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000b000000-0x000000000b01ffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000b020000-0x00000000bb718fff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bb719000-0x00000000bcd36fff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bcd37000-0x00000000bcd81fff] ACPI data
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bcd82000-0x00000000bd461fff] ACPI NVS
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bd462000-0x00000000bdffefff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bdfff000-0x00000000beffffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bf000000-0x00000000bfffffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000f0000000-0x00000000f7ffffff] reserved
lines 1-28





























Apr 15 08:45:04 localhost kernel: Linux version 5.14.21-150400.24.55-default (geeko@buildhost) (gcc (SUSE Linux) 7.5.0,>
Apr 15 08:45:04 localhost kernel: Command line: BOOT_IMAGE=/boot/vmlinuz-5.14.21-150400.24.55-default root=UUID=59b1316>
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x200: 'Protection Keys User registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Apr 15 08:45:04 localhost kernel: x86/fpu: xstate_offset[9]:  832, xstate_sizes[9]:    8
Apr 15 08:45:04 localhost kernel: x86/fpu: Enabled xstate features 0x207, context size is 840 bytes, using 'compacted' >
Apr 15 08:45:04 localhost kernel: signal: max sigframe size: 3376
Apr 15 08:45:04 localhost kernel: BIOS-provided physical RAM map:
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009d3ff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000009d400-0x000000000009ffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000000100000-0x0000000009bfefff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000009bff000-0x0000000009ffffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a000000-0x000000000a1fffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a200000-0x000000000a20dfff] ACPI NVS
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a20e000-0x000000000affffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000b000000-0x000000000b01ffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000b020000-0x00000000bb718fff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bb719000-0x00000000bcd36fff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bcd37000-0x00000000bcd81fff] ACPI data
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bcd82000-0x00000000bd461fff] ACPI NVS
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bd462000-0x00000000bdffefff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bdfff000-0x00000000beffffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bf000000-0x00000000bfffffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000f0000000-0x00000000f7ffffff] reserved
lines 1-28...skipping...
Apr 15 08:45:04 localhost kernel: Linux version 5.14.21-150400.24.55-default (geeko@buildhost) (gcc (SUSE Linux) 7.5.0, GNU ld (GNU Binuti>
Apr 15 08:45:04 localhost kernel: Command line: BOOT_IMAGE=/boot/vmlinuz-5.14.21-150400.24.55-default root=UUID=59b13169-c3b1-4a17-b03a-e5>
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x200: 'Protection Keys User registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Apr 15 08:45:04 localhost kernel: x86/fpu: xstate_offset[9]:  832, xstate_sizes[9]:    8
Apr 15 08:45:04 localhost kernel: x86/fpu: Enabled xstate features 0x207, context size is 840 bytes, using 'compacted' format.
Apr 15 08:45:04 localhost kernel: signal: max sigframe size: 3376
Apr 15 08:45:04 localhost kernel: BIOS-provided physical RAM map:
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009d3ff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000009d400-0x000000000009ffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000000100000-0x0000000009bfefff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000009bff000-0x0000000009ffffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a000000-0x000000000a1fffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a200000-0x000000000a20dfff] ACPI NVS
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a20e000-0x000000000affffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000b000000-0x000000000b01ffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000b020000-0x00000000bb718fff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bb719000-0x00000000bcd36fff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bcd37000-0x00000000bcd81fff] ACPI data
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bcd82000-0x00000000bd461fff] ACPI NVS
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bd462000-0x00000000bdffefff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bdfff000-0x00000000beffffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bf000000-0x00000000bfffffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000f0000000-0x00000000f7ffffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000fd200000-0x00000000fd2fffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000fd600000-0x00000000fd7fffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000fea00000-0x00000000fea0ffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000feb80000-0x00000000fec01fff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000fec10000-0x00000000fec10fff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000fec30000-0x00000000fec30fff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000fed00000-0x00000000fed00fff] reserved
lines 1-35


































Apr 15 08:45:04 localhost kernel: Linux version 5.14.21-150400.24.55-default (geeko@buildhost) (gcc (SUSE Linux) 7.5.0, GNU ld (GNU B>
Apr 15 08:45:04 localhost kernel: Command line: BOOT_IMAGE=/boot/vmlinuz-5.14.21-150400.24.55-default root=UUID=59b13169-c3b1-4a17-b0>
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: Supporting XSAVE feature 0x200: 'Protection Keys User registers'
Apr 15 08:45:04 localhost kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Apr 15 08:45:04 localhost kernel: x86/fpu: xstate_offset[9]:  832, xstate_sizes[9]:    8
Apr 15 08:45:04 localhost kernel: x86/fpu: Enabled xstate features 0x207, context size is 840 bytes, using 'compacted' format.
Apr 15 08:45:04 localhost kernel: signal: max sigframe size: 3376
Apr 15 08:45:04 localhost kernel: BIOS-provided physical RAM map:
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009d3ff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000009d400-0x000000000009ffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000000100000-0x0000000009bfefff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x0000000009bff000-0x0000000009ffffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a000000-0x000000000a1fffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a200000-0x000000000a20dfff] ACPI NVS
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000a20e000-0x000000000affffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000b000000-0x000000000b01ffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x000000000b020000-0x00000000bb718fff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bb719000-0x00000000bcd36fff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bcd37000-0x00000000bcd81fff] ACPI data
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bcd82000-0x00000000bd461fff] ACPI NVS
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bd462000-0x00000000bdffefff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bdfff000-0x00000000beffffff] usable
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000bf000000-0x00000000bfffffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000f0000000-0x00000000f7ffffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000fd200000-0x00000000fd2fffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000fd600000-0x00000000fd7fffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000fea00000-0x00000000fea0ffff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000feb80000-0x00000000fec01fff] reserved
Apr 15 08:45:04 localhost kernel: BIOS-e820: [mem 0x00000000fec10000-0x00000000fec10fff] reserved
lines 1-33

the only things that appear at the terminal with this journal cmd was that

**Comment by stuarthayhurst** [comment]
Ok, can you do `sudo journalctl -f`, then launch the preferences window, and copy the output from that please? That should capture the log during the error, instead of the whole system log.

**Comment by joaoseixas88** [comment]
> Ok, can you do `sudo journalctl -f`, then launch the preferences window, and copy the output from that please? That should capture the log during the error, instead of the whole system log.
Apr 15 09:10:54 localhost.localdomain sudo[3730]: pam_unix(sudo:session): session opened for user root by (uid=1000)
Apr 15 09:10:57 localhost.localdomain gnome-shell[2652]: g_settings_get_enum() called on key 'control-nightlight' which is not associated with an enumerated type
Apr 15 09:10:57 localhost.localdomain gnome-shell[2652]: g_settings_get_enum() called on key 'control-nightlight' which is not associated with an enumerated type
Apr 15 09:11:09 localhost.localdomain systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Apr 15 09:11:09 localhost.localdomain systemd[1]: systemd-localed.service: Deactivated successfully.
Apr 15 09:11:13 localhost.localdomain dbus-daemon[2509]: [session uid=1000 pid=2509] Activating service name='org.gnome.Shell.Extensions' requested by ':1.17' (uid=1000 pid=2652 comm="/usr/bin/gnome-shell ")
Apr 15 09:11:13 localhost.localdomain dbus-daemon[2509]: [session uid=1000 pid=2509] Successfully activated service 'org.gnome.Shell.Extensions'
Apr 15 09:11:13 localhost.localdomain gjs[3750]: JS ERROR: Failed to open preferences: SyntaxError: expected property name, got '{' @ /home/joaoseixas/.local/share/gnome-shell/extensions/caffeine@patapon.info/prefs.js:408
Apr 15 09:11:23 localhost.localdomain geoclue[1905]: Service not used for 60 seconds. Shutting down..
Apr 15 09:11:23 localhost.localdomain systemd[1]: geoclue.service: Deactivated successfully.
Apr 15 09:11:26 localhost.localdomain PackageKit[1912]: refresh-cache transaction /1_dbbcbebd from uid 1000 finished with success after 46019ms
Apr 15 09:11:26 localhost.localdomain gnome-software[2858]: adding wildcard app */*/*/org.gnome.Builder.desktop/* to plugin cache
Apr 15 09:11:26 localhost.localdomain gnome-software[2858]: adding wildcard app */*/*/org.gnome.Calculator.desktop/* to plugin cache
Apr 15 09:11:26 localhost.localdomain gnome-software[2858]: adding wildcard app */*/*/org.gnome.clocks.desktop/* to plugin cache
Apr 15 09:11:26 localhost.localdomain gnome-software[2858]: adding wildcard app */*/*/org.gnome.Dictionary.desktop/* to plugin cache
Apr 15 09:11:26 localhost.localdomain gnome-software[2858]: adding wildcard app */*/*/org.gnome.Documents.desktop/* to plugin cache
Apr 15 09:11:26 localhost.localdomain gnome-software[2858]: adding wildcard app */*/*/org.gnome.Evince/* to plugin cache
Apr 15 09:11:26 localhost.localdomain gnome-software[2858]: adding wildcard app */*/*/org.gnome.gedit.desktop/* to plugin cache
Apr 15 09:11:26 localhost.localdomain gnome-software[2858]: adding wildcard app */*/*/org.gnome.Maps.desktop/* to plugin cache
Apr 15 09:11:26 localhost.localdomain gnome-software[2858]: adding wildcard app */*/*/org.gnome.Weather/* to plugin cache
Apr 15 09:11:26 localhost.localdomain gnome-software[2858]: Only 0 apps for recent list, hiding
Apr 15 09:11:26 localhost.localdomain Zypp-main[1912]: docker-ce-stable is not cached! Do a refresh
Apr 15 09:11:27 localhost.localdomain PackageKit[1912]: resolve transaction /2_aedcdabd from uid 1000 finished with success after 887ms
Apr 15 09:11:27 localhost.localdomain PackageKit[1912]: resolve transaction /3_cebaddee from uid 1000 finished with success after 0ms
Apr 15 09:11:27 localhost.localdomain gnome-software[2858]: Only 8 apps for popular list, hiding
Apr 15 09:11:39 localhost.localdomain dbus-daemon[2509]: [session uid=1000 pid=2509] Activating via systemd: service name='org.gtk.vfs.Metadata' unit='gvfs-metadata.service' requested by ':1.17' (uid=1000 pid=2652 comm="/usr/bin/gnome-shell ")
Apr 15 09:11:39 localhost.localdomain systemd[2467]: Starting Virtual filesystem metadata service...
Apr 15 09:11:39 localhost.localdomain dbus-daemon[2509]: [session uid=1000 pid=2509] Successfully activated service 'org.gtk.vfs.Metadata'
Apr 15 09:11:39 localhost.localdomain systemd[2467]: Started Virtual filesystem metadata service.

**Comment by joaoseixas88** [comment]
property name, got '{' @ /home/joaoseixas/.local/share/gnome-shell/extensions/[caffeine@patapon.info](mailto:caffeine@patapon.info)/prefs.js:408 I guess thats the line you want

**Comment by pakaoraki** [comment]
Hi, which linux distrib and gnome version are you using ?

**Comment by joaoseixas88** [comment]
> Hi, which linux distrib and gnome version are you using ?

OpenSUSE leap 15.4. At this right moment im installing the opemnSUSE tumbleweed

**Comment by pakaoraki** [comment]
There is a similar issue with Gnome 40 and Caffeine V42 here: #218 

If you're using an old version of Caffeine with Gnome 40 or older, you can try this version:
```
git clone --branch gnome-shell-40 https://github.com/pakaoraki/gnome-shell-extension-caffeine.git
cd gnome-shell-extension-caffeine
make build
make install
```

**Comment by joaoseixas88** [comment]
> There is a similar issue with Gnome 40 and Caffeine V42 here: #218
> 
> If you're using an old version of Caffeine with Gnome 40 or older, you can try this version:
> 
> ```
> git clone --branch gnome-shell-40 https://github.com/pakaoraki/gnome-shell-extension-caffeine.git
> cd gnome-shell-extension-caffeine
> make build
> make install
> ```


Im installing tumbleweed right now, if I got the same error Ill try this and give you the feedback

**Comment by stuarthayhurst** [comment]
> > Hi, which linux distrib and gnome version are you using ?
> 
> OpenSUSE leap 15.4. At this right moment im installing the opemnSUSE tumbleweed

Tumbleweed has a much newer GNOME, so the latest version of Caffeine should run fine on it, without the error.

**Comment by joaoseixas88** [comment]
> > > Hi, which linux distrib and gnome version are you using ?
> > 
> > 
> > OpenSUSE leap 15.4. At this right moment im installing the opemnSUSE tumbleweed
> 
> Tumbleweed has a much newer GNOME, so the latest version of Caffeine should run fine on it, without the error.

Thats why Ill try. Some of my fav gnome estensions was not working properly or are not even compatible

**Comment by stuarthayhurst** [comment]
@joaoseixas88 Did you have any luck fixing this with Tumbleweed?

**Comment by stuarthayhurst** [comment]
Closing, as the lines with an issue aren't even present in the latest version. If there's still a problem on the latest version, it would be under a new issue anyway.
