### ISSUE TITLE
CLI options do not work

### ISSUE THREAD

**Issue by cewbdex** [eonpatapon/gnome-shell-extension-caffeine#257]
When I want to enable Caffeine from command line, it does not work, when I get the value, it shows proper true/false, however, when I change it via command, I get the desired true/false via command, but it does not control the actual Caffeine on/off state (icon is still the same, no changes).

**Comment by pakaoraki** [comment]
Hi, the command line are still working but we forgot to update the documentation, I'll fix that.

```
# Enable
gsettings --schemadir ~/.local/share/gnome-shell/extensions/caffeine@patapon.info/schemas/ set org.gnome.shell.extensions.caffeine toggle-state true

# Disable
gsettings --schemadir ~/.local/share/gnome-shell/extensions/caffeine@patapon.info/schemas/ set org.gnome.shell.extensions.caffeine toggle-state false
```
