### ISSUE TITLE
Caffeine icon disappears after lock or gnome restart.

### ISSUE THREAD

**Issue by viking-pl** [eonpatapon/gnome-shell-extension-caffeine#26]
Caffeine icon disappears after lock or gnome restart. 
This does not seem to affect Caffeine's functioning, but, obviously disallows hot/cold coffee switching
Icon can be brought back using IconHider.
## 

Fedora 20
Gallium 0.4 on AMD RV635
Gnome Version 3.10.2

**Comment by jonafato** [comment]
This issue seems more related to icon-hider than Caffeine. Can it be closed?
