### ISSUE TITLE
Incorrect position in the quick settings menu

### ISSUE THREAD

**Issue by miah-7** [eonpatapon/gnome-shell-extension-caffeine#261]
Fedora 38
GNOME 44

![image](https://user-images.githubusercontent.com/127752487/233163007-b4628b91-c2bc-4229-903f-5fd0ba9038a9.png)

**Comment by stuarthayhurst** [comment]
Should be the same as #249, fixed by #250

**Comment by miah-7** [comment]
> Should be the same as #249, fixed by #250
> 
> Can't remember if this has made it to a release, can you try running the latest `master`?
> 
> Thanks

Latest master works fine

**Comment by stuarthayhurst** [comment]
@eonpatapon Since GNOME 44 has been released, is it worth pushing a new release? We're probably going to keep getting these reports for a while otherwise.

**Comment by miah-7** [comment]
> @eonpatapon Since GNOME 44 has been released, is it worth pushing a new release? We're probably going to keep getting these reports for a while otherwise.

I don't see any reason to wait
