### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by iluvgirlswithglasses** [eonpatapon/gnome-shell-extension-caffeine#282]
How did you add the Caffeine button into the applet? And how would you remove/add other buttons? Thanks!

![image](https://github.com/eonpatapon/gnome-shell-extension-caffeine/assets/58514512/289a9237-94b4-43bb-aea4-dbf897a823a1)

**Comment by stuarthayhurst** [comment]
Take a look here: https://gjs.guide/extensions/topics/quick-settings.html#toggle-menu

**Comment by iluvgirlswithglasses** [comment]
Thanks! The document has everything I need!
