### ISSUE TITLE
Wrong v51 release (Gnome 44) & versioning issue

### ISSUE THREAD

**Issue by pakaoraki** [eonpatapon/gnome-shell-extension-caffeine#302]
After some investigation on #222, I figure out that the bug #285 is back for `Gnome 44` (Fullscreen inhibit gets stuck due to a race condition) with the version v51 from gnome extension page. 

In fact, the fix is missing and after a quick comparison, it's seams that's the code from [gnome-shell-43-44](https://github.com/eonpatapon/gnome-shell-extension-caffeine/tree/gnome-shell-43-44) branch is not the one from the version [v51](https://extensions.gnome.org/extension/517/caffeine/) available.

I'm also a bit confuse about the mismatch between version in GitHub repository and gnome extension page: 

- for `Gnome 45`: v50 is v52.
- for `Gnome 44`: v49 is v51.

The `metadata.json` file have been rewritten by a tool named `SweetTooth`: so I guess it's part of the release process but I'm not very familiar with it.

@eonpatapon : can you confirm the issue with v51 release please ?

**Comment by stuarthayhurst** [comment]
> The `metadata.json` file have been rewritten by a tool named `SweetTooth`: so I guess it's part of the release process but I'm not very familiar with it.

Yea, the bundle gets unzipped, the metadata is rewritten by SweetTooth and then it's repacked. Regardless of the number you give as the version, SweetTooth will strip it out and replace it with the next numerical version, following on from the last uploaded release (including rejected uploads).

**Comment by pakaoraki** [comment]
Maybe we could match the github version number with the release ? what do you think ?

**Comment by stuarthayhurst** [comment]
Makes sense to do it. I had to do that to my extensions a few times in the past anyway.

**Comment by eonpatapon** [comment]
I'm trying to have the same versions, but it's not easy as when you upload to e.g.o it will not use the version defined in the metadata, it will just take the next integer of the previous upload. It's easy to mess things up when you re-upload, upload for an old version etc...

**Comment by stuarthayhurst** [comment]
Closing, as there's not much to do here, except syncing it at release time when things fall out of sync
