### ISSUE TITLE
Caffeine RPM is not importing its Gschema to /usr/share/glib-2.0/schemas

### ISSUE THREAD

**Issue by fiftydinar** [eonpatapon/gnome-shell-extension-caffeine#312]
For this reason, gsettings cannot see caffeine schema, but dconf can.

Just set in RPM spec file to copy this to /usr/share/glib-2.0/schemas & problem will be solved.

**Comment by stuarthayhurst** [comment]
We don't provide an RPM upstream, you'll have to contact the distro maintainers for this

**Comment by fiftydinar** [comment]
Thanks for information
