### ISSUE TITLE
Minor issue on GNOME 46

### ISSUE THREAD

**Issue by hendersj** [eonpatapon/gnome-shell-extension-caffeine#320]
Looking at the latest version on extensions.gnome.org, it shows an "Error" state for this extension. It seems to work OK, but looking in Looking Glass, I see this:

![image](https://github.com/eonpatapon/gnome-shell-extension-caffeine/assets/2662071/e8326348-8d1b-4045-bb32-f71e0c4fb906)

Hopefully an easy issue to fix.

**Comment by stuarthayhurst** [comment]
The port for the extension is at #317, the latest release doesn't support GNOME 46 yet

**Comment by hendersj** [comment]
Cool, thanks.  I searched for "46" before opening this, and didn't find any results.  Should've scanned the more recent open tickets as well.

I'll go ahead and close this one since it's being addressed.  Thanks again.
