### ISSUE TITLE
Add gnome 46 support

### ISSUE THREAD

**Issue by AnyCreatureMorph** [eonpatapon/gnome-shell-extension-caffeine#321]
Please update this extension i'm running openSUSE tumbleweed and I got the latest gnome in day 1.

**Comment by bulletmark** [comment]
GNOME 46 released mainstream on Arch now so this bug is very prominent.

**Comment by stuarthayhurst** [comment]
GNOME 46 support is in #317, I can merge that but it won't do anything since @eonpatapon handles releases

However, if you want to install from that branch, I'd appreciate any additional testing :)

**Comment by bulletmark** [comment]
@stuarthayhurst I installed your PR branch on my Arch box and seems to work fine, although I had to go to settings to restore some of the behavior I had previously. Thanks.

**Comment by eonpatapon** [comment]
Latest release uploaded to e.g.o supports GNOME 46

Thanks @stuarthayhurst !
