### ISSUE TITLE
It doesn't turn on

### ISSUE THREAD

**Issue by AxelSkye** [eonpatapon/gnome-shell-extension-caffeine#322]
The UI appears, but it doesn't hange any energy setting when it's enables and screen goes off and PC suspends anyway. It happens to me on Gnome 46, Fedora 40 beta

**Comment by stuarthayhurst** [comment]
Is this #311 again?

**Comment by pakaoraki** [comment]
I ran some tests on Fedora 40 in a virtual machine and it seams to work fine, I wasn't able to reproduce this.
After full update of the system + reboot, can you try to run this command:

```
for inhibitor in $(dbus-send --print-reply --dest=org.gnome.SessionManager /org/gnome/SessionManager org.gnome.SessionManager.GetInhibitors | grep object | grep -o '".*"' | tr -d '"'); do dbus-send --print-reply --dest=org.gnome.SessionManager $inhibitor org.gnome.SessionManager.Inhibitor.GetAppId && dbus-send --print-reply --dest=org.gnome.SessionManager $inhibitor org.gnome.SessionManager.Inhibitor.GetReason | grep string; done
```

When Caffeine is enabled, it should return something like:
```
   string "user"
   string "Inhibit by Caffeine"
```

**Comment by AxelSkye** [comment]
Okay, don't ask me what changed but after last updates in F40 it got fixed, thanks.
