### ISSUE TITLE
Feature Request: trigger for specyfic processes/binaries

### ISSUE THREAD

**Issue by LukIsHere** [eonpatapon/gnome-shell-extension-caffeine#331]
so  currently when i do:
- git clone
- wget
- curl
- make
- etc.

if i want extension to trigger i have to set it on entire terminal
and after the command is done the extension is still triggered despite the fact that after that in some cases it should go off since it's not needed
it would be nice to add these processes to the list of apps or somewhere else so my device doesn't go to sleep while downloading or compiling sth

**Comment by eonpatapon** [comment]
Hello, I don't think we can track reliably cli apps like we can do with graphical apps.

If you'd like to enable automatically Caffeine when running such cli tools I'd suggest to use some kind of wrapper which will use the following command to enable/disable Caffeine from the cli: https://github.com/eonpatapon/gnome-shell-extension-caffeine?tab=readme-ov-file#cli

**Comment by stuarthayhurst** [comment]
Yeah, we can only track something recognised by GNOME's AppSystem, and that seems to be anything with a .desktop entry, so unfortunately we can't do anything with those CLI programs.
