### ISSUE TITLE
Caffeine turns off when exiting full screen app, regardless of previous state [version 51]

### ISSUE THREAD

**Issue by matgaj** [eonpatapon/gnome-shell-extension-caffeine#343]
If the option to enable Caffeine when a fullscreen app launches is enabled, closing the app will disable Caffeine, regardless of the state prior to launching the fullscreen app.

Ideally, it would return to the previous state or simply do nothing if Caffeine is already running when a fullscreen app is launched. That is because, another process could be running in the background that requires the computer not to enter suspend, while it is still being used by the user. If a user opens and closes a fullscreen app, then leaves the computer, it will enter suspend and stop the running process.

I'm running v51 on Debian 12.7. Consider backporting a fix?

**Comment by matteioo** [comment]
This also happens on Fedora 40.
