### ISSUE TITLE
Quick settings tile on multiple monitors

### ISSUE THREAD

**Issue by sinus-x** [eonpatapon/gnome-shell-extension-caffeine#350]
Hello.
I've noticed that the quick settings tile gets only added to the primary monitor. Would it be possible to get it added to all connected monitors instead? In the current state it makes the menus inconsistent and items after this one jump around depending on which monitor's menu you've chosen.
Thank you for the maintenance!

**Comment by stuarthayhurst** [comment]
I'm not sure I follow, how would is be added to other monitors? There's only one quick settings menu, and that's on the primary monitor.

Are you using an extension that changes this?
