### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by prescott66** [eonpatapon/gnome-shell-extension-caffeine#42]
I have created slovak translation of your great extension.
I dont know how to create pull request with binary file (.MO), so i have uploaded my translation to my public dropbox.
Here is link:

https://www.dropbox.com/s/537gt07pn8bbx0b/caffeine-slovak-translation.tar.gz?dl=0

Please commit it.
Thank You!

**Comment by DoctorJellyface** [comment]
Dikes.

**Comment by eonpatapon** [comment]
Thank you
