### ISSUE TITLE
Screen starts to black out immediately after exiting full-screen

### ISSUE THREAD

**Issue by jurf** [eonpatapon/gnome-shell-extension-caffeine#44]
You wouldn't believe how hard it is to create a title for this bug.

How to reproduce:
1. Turn "Enable when a full-screen application is running" to on.
2. Watch something in a full-screen window for long enough.
3. Exit full-screen. You will now notice the screen starts to slowly black out. You have to wiggle the mouse or something to stop it.

**Comment by stuarthayhurst** [comment]
Can this still be reproduced? I tested this with timers, and it works as expected, so I doubt it's still broken for fullscreen, but shouldn't be too complicated to fix if not.

**Comment by stuarthayhurst** [comment]
Closing, as this is a 9 year old bug that can't be reproduced. Something probably fixed this within GNOME a while ago.
