### ISSUE TITLE
Debian Jessie Extenstion Error

### ISSUE THREAD

**Issue by mudongliang** [eonpatapon/gnome-shell-extension-caffeine#49]
Debian Jessie , Gnome 3.14.
Today I updated Caffeine Extension, but after that errors happened:
![screenshot from 2015-10-11 16 21 39](https://cloud.githubusercontent.com/assets/6214861/10415967/2e2b0d0e-7034-11e5-872e-87994811d1b9.png)
I don't know where the error log stores. If you want to have more error information, tell me how to get it.

**Comment by eonpatapon** [comment]
Try to look into .xsession-errors

**Comment by mudongliang** [comment]
It is a strange behavior. When I open my system tonight, I find that the
error disappears. It works now.
Thank you.

2015-10-12 23:19 GMT+08:00 Jean-Philippe Braun <notifications@github.com>:
