### ISSUE TITLE
Some language strings shown in English instead of regional language

### ISSUE THREAD

**Issue by big-ant** [eonpatapon/gnome-shell-extension-caffeine#50]
Hi Jean-Philippe

The language strings "auto suspend and screensaver disabled/ enabled" are still showing up in English instead of German. I thought it's a version issue, but it's still in your current version released a few days ago ...And as far as I see it's the same for the configuration strings added more recently, like "enable when a fullscreen app is running".

When changing to "francais" it seems to works for French, but not for Spanish either.
What could be the issue here? I'm using Fedora 22.

Cheers, Roman

**Comment by eonpatapon** [comment]
I think that the mo file is outdated. I will regenerate it.

For the spanish version the translation is missing.

**Comment by big-ant** [comment]
Thank you. I didn't check the mo file.
Cheers
Roman
Am Sonntag, den 18.10.2015, 05:41 -0700 schrieb Jean-Philippe Braun:
