### ISSUE TITLE
Disable caffeine automatically on manual lock

### ISSUE THREAD

**Issue by ijanos** [eonpatapon/gnome-shell-extension-caffeine#53]
Every time when I lock my screen it means that I don't need the caffeine feature any more but I tend to forget to turn off caffeine.

It would be great if it automatically disables itself when I lock the screen or put the machine to sleep manually.

**Comment by eljenso** [comment]
Caffeine is now disabled after locking.
Not sure about sleeping, can't test this.

**Comment by ijanos** [comment]
Great! Thank you! I'm waiting for the e.g.o update then I will check this out and close this.

**Comment by eonpatapon** [comment]
Updated on e.g.o

**Comment by ijanos** [comment]
Works great! Thank you!

**Comment by Tom743** [comment]
Can you add an option to make this happen again? I just want to download a big file on my laptop and not use so much battery, would be nice if I could lock the screen (that would turn it off) and keep downloading the file (preventing the computer from suspending).
