### ISSUE TITLE
Implement options for restoring state

### ISSUE THREAD

**Issue by eljenso** [eonpatapon/gnome-shell-extension-caffeine#58]
After using the current version for a while, I think it would be a good idea to implement options for when to auto-disable caffeine.
Often I lock the screen when I walk away from my laptop and would like caffeine to be enabled when I come back.

Currently caffeine does not restore the state. Hence, caffeine will be disabled after locking the screen or restart of the system.

Options to enable restores after locking the screen and/or system restart would be good.

**Comment by Th3Z0ne** [comment]
Please bring the behaviour back, so that Caffeine remembers its state during the machine being locked.
It's behaviour was perfect before the last update.

**Comment by eonpatapon** [comment]
Can you test the code in this branch ?

Thanks

**Comment by Th3Z0ne** [comment]
Works perfectly fine! Tested on GNOME Shell 3.16.4 - installed through the gnome tweak tool.

Thank you! Thanks!
