### ISSUE TITLE
Add keyboard shortcut option

### ISSUE THREAD

**Issue by eljenso** [eonpatapon/gnome-shell-extension-caffeine#61]
For those of us who don't like using the mouse. :-)

**Comment by gergelypolonkai** [comment]
Me too :)

Also, I know choosing a good hotkey is hard, but if it can be changed, it can be disabled by default.

**Comment by corebots** [comment]
a shortcut option would be nice!

**Comment by darthzen** [comment]
+1 from me!

**Comment by SirZayers** [comment]
+1

**Comment by MeanderingCode** [comment]
The PR #205 has been open for months. Please consider merging.
