### ISSUE TITLE
(Option to?) Integrate with system menu

### ISSUE THREAD

**Issue by dsboger-zz** [eonpatapon/gnome-shell-extension-caffeine#68]
This is a proposal for a possible aesthetic enhancement, so of minor importance. Feel free to "won't fix" it.

Would it be possible to move the enable/disable action into the system menu, similar to e.g. the wifi menu? Also, the indicator would be invisible when caffeine is disabled, but would be visible together with the other system indicators (e.g. wifi, volume, battery, etc.) when active?

Thanks for your efforts!

**Comment by blahax2g** [comment]
It can be something like in this issue: #81 
![caffeine-menu](https://user-images.githubusercontent.com/29534847/35778948-d31c859a-09c5-11e8-9999-63af6655224e.png)

**Comment by eonpatapon** [comment]
We can close this since https://github.com/eonpatapon/gnome-shell-extension-caffeine/pull/216 is merged
