### ISSUE TITLE
Not showing up in Gnome-Software

### ISSUE THREAD

**Issue by brittyazel** [eonpatapon/gnome-shell-extension-caffeine#74]
I see that this extension works fine with Gnome 3.22, but it is not showing up by default in extensions.gnome.org when sorting by "current gnome version", and only shows up if you select "all versions". Further, this addon does not show up in Gnome-Software, probably for the same reasons as above.
I don't know if it is just a flag that must be set to broadcase gnome 3.22 support, but please do it. This addon is incredible.

**Comment by eonpatapon** [comment]
I've uploaded it on e.g.o
