### ISSUE TITLE
When using top bar through keyboard, can't toggle Caffeine

### ISSUE THREAD

**Issue by stickster** [eonpatapon/gnome-shell-extension-caffeine#75]
Regardless of whether there there's a specific or configurable key combination for Caffeine, if I use a keyboard to access the GNOME top bar via Ctrl+Alt+Tab, I should be able to hit Enter on the Caffeine icon to toggle it. This doesn't seem to work under GNOME 3.22.

**Comment by umpirsky** [comment]
Any updates on this? I can navigate to it from keyboard, but cannot toggle with `Enter`.

**Comment by stuarthayhurst** [comment]
Should be fixed by #216, as it's now in the Quick Settings menu

**Comment by stuarthayhurst** [comment]
Closing, as #216 has been merged and released
