### ISSUE TITLE
delay time between shutdown select and when windows appears

### ISSUE THREAD

**Issue by julesx81** [eonpatapon/gnome-shell-extension-caffeine#76]
On click on shutdown button inside the top menu (ref. attach. n.1) the delay time until the windows appear are about 30 seconds. Occur only on the first time on the session.
**Case 1: caffeine disabled**
    instantly windows appear.
**Case 2: caffeine enabled**
    first selection 30 seconds for windows appear.
**Case 3: caffeine enabled - with the second attempt**
    first selection 30 seconds for windows appear, then i press cancel button. On second attempt the windows appear instantly.
**Case 4: caffeine enabled - gnome-shell restarted**
    after case 3 i restart gnome-shell and the issue return.

Thank you 4 your time.
Bye
Lorenzo.

![screenshot from 2016-11-12 16-36-22](https://cloud.githubusercontent.com/assets/11043075/20239086/920b3ed6-a8f8-11e6-9c99-e05131380312.png)

**Comment by truongan** [comment]
I believe this maybe related to #67

**Comment by eonpatapon** [comment]
Duplicate #48 #67
