### ISSUE TITLE
[Ubuntu unity] How to access settings?

### ISSUE THREAD

**Issue by wolass** [eonpatapon/gnome-shell-extension-caffeine#78]
I cant seem to get to the GUI. The indicator works well and I can turn it on and off. The problem is that i cant add any custom apps that caffeine should inhibit. 

Do I have to install any GNOME packages for this to work on a new ubuntu 16.10 install?
Or is there a text file that I can directly access to add the apps i want?

**Comment by eonpatapon** [comment]
You can run gnome-shell-extension-prefs to access all extensions settings.

BTW, unity != gnome-shell, it's a completely different desktop interface.

**Comment by wolass** [comment]
Yeah but gnome-shell is not a prerequisite to run caffeine right?

**Comment by eonpatapon** [comment]
This is the repo of the gnome-shell extension so yes
