### ISSUE TITLE
Show in (top panel XOR aggregate menu)

### ISSUE THREAD

**Issue by jplitza** [eonpatapon/gnome-shell-extension-caffeine#81]
I think it would be nice to show a setting in the aggregate menu instead of the top panel, at least if the icon in the top panel is disabled. [gnome-shell-extension-redshift](/tommie-lie/gnome-shell-extension-redshift) does this, and it saves space while still having the setting nearby.

![grafik](https://cloud.githubusercontent.com/assets/3628012/21594065/58c02422-d11e-11e6-8fb6-be44ae120551.png)

**Comment by stuarthayhurst** [comment]
Covered by #216
