### ISSUE TITLE
Preferences dialog won't load on GNOME 3.24

### ISSUE THREAD

**Issue by greatquux** [eonpatapon/gnome-shell-extension-caffeine#83]
GNOME 3.24 contains a newer version of GJS which has stricter JavaScript rules, e.g. you can't redeclare variables.  When trying to bring up the preferences box I get:

TypeError: redeclaration of let hbox

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49

**Comment by PHLAK** [comment]
Same issue here. Waiting for update.
