### ISSUE TITLE
Can't add applications not listed in menu

### ISSUE THREAD

**Issue by Enigma0** [eonpatapon/gnome-shell-extension-caffeine#87]
Trying to add Plex Media Player and Kodi - neither are listed in the menu.

Is there some file I can add the process names to?

**Comment by criztovyl** [comment]
Caffeine works with App-IDs which you could add manually to it's dconf/gconf/chooseonebutnotboth at `/org/gnome/shell/extensions/caffeine/inhibit-apps`.
You can get an Apps App-Id by locating it's `.desktop` file; by convention the file name is equal to the App-Id.

**Comment by Enigma0** [comment]
The location `/org/gnome/shell/extensions/caffeine/inhibit-apps/ doesn't exist on my system. I'm on Ubuntu GNOME 16.10 - would it be somewhere else?

I do have:
```
ls .local/share/applications/ | grep plex
plexmediaplayer.desktop
plexmediaplayer_web.desktop

ls /usr/share/applications/ | grep kodi
kodi.desktop
```

**Comment by criztovyl** [comment]
Uhm, sry, didn't made that clear enough :D

The path isn't a filesystem path, it's a dconf path.

Just try `dconf-editior` (Editor) or `dconf` (cli only).

**Comment by Enigma0** [comment]
Ah woops - that makes more sense - I've never used that utility.

I have `['plexmediaplayer', 'plexmediaplayer_web', 'kodi']` in there now.

**Comment by criztovyl** [comment]
That should be it. Does it work?
If not there must be another way to get the (real) application id.

**Comment by Enigma0** [comment]
@criztovyl It does not appear to no.

I launched PMP full screen and then windowed it and Caffeine re-enabled screensaver.

**Comment by criztovyl** [comment]
It seems like the AppID includes the `.desktop` part.

Also maybe try to get the AppID from the window manager via gjs:
  - get the PID of the program (`pgrep --list-name plex`)
  - open the Gnome Looking Glass (Alt+F2 and then enter `lg`)
  - run:
    - `wt = new Shell.WindowTracker()` and
    - `wt.get_app_from_pid(<pid here>).get_id()`

That should give you the AppID.

**Comment by Enigma0** [comment]
@criztovyl Awesome - yeah it was missing the `.desktop`.
