### ISSUE TITLE
Gnome 3.24

### ISSUE THREAD

**Issue by jesusignazio** [eonpatapon/gnome-shell-extension-caffeine#93]
Support Gnome 3.24

**Comment by lolow** [comment]
Error when clicking on preferences in the tweek tool (v3.24)
TypeError: redeclaration of let hbox

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49

**Comment by dffischer** [comment]
Caffeine seems to work fine with Gnome 3.24 on my Arch Linux machine running Wayland.

I cannot observe the message @lolow describes and speculate, it may have been solved by commit ee3ff6246c71d49e1ee544d9bc35493415cec749.

**Comment by dw72** [comment]
I have same effect like @lolow

**Comment by ogarcia** [comment]
I have similar problem that @lolow and I cannot make click over caffeine icon in top bar (it do nothing). I'm running gnome with xorg.

I discover a workaround that is lock my session, enter password and unlock, and then I can make click and activate / deactivate caffeine.

**Comment by gmellini** [comment]
I installed caffeine from github (I had the same preference issue installing from gnome web site).
Whit github versione I can access preference dialog, but caffeine icon often hangs and I uninstalled it 
I'm on Ubuntu Gnome 17.04

**Comment by smcv** [comment]
This seems to have been fixed in #84, #90.

**Comment by jonafato** [comment]
It looks like this is fixed. Can the issue be closed?
