### ISSUE TITLE
Redeclaration of let hbox - Solus Gnome

### ISSUE THREAD

**Issue by hhiru** [eonpatapon/gnome-shell-extension-caffeine#95]
> TypeError: redeclaration of let hbox
> 
> Stack trace:
>   Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
>   Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
>   Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
>   wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
>   main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
>   @<main>:1:49
>   

This is the error. The extension seems to work fine since it is showed in the topbar and I can enable and disable it but if I try to open the preferences panel this is the error I get. Also the screensaver is not disable at all, probably due to the error I mentioned above

Solus 2017.04.18.0 64-bit

**Comment by pierrre** [comment]
Same on Arch Linux, Gnome 3.24

**Comment by Enigma0** [comment]
Same on Ubuntu GNOME 17.04.

**Comment by lsatenstein** [comment]
This problem is reappearing with Fedora26 beta (to be the production version).  Take Caffeine as is, as attempting to configure it locks up gnome for the user.

**Comment by eonpatapon** [comment]
Already fixed in master by ee3ff62

**Comment by Enigma0** [comment]
Confirm fixed for me.
